# Generated by Django 4.1.3 on 2022-12-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True, default='null'),
            preserve_default=False,
        ),
    ]
